name: Run Backend UT

on: 
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy'
        required: true
        default: 'main'
  push:
    branches: 
        - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploying branch
        run: |
          echo ${{ github.event.inputs.branch || 'main' }}

      - name: Print PATH
        run: echo $PATH

      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.13.0'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm install
      
      - name: Run tests
        run: npm test
              
